name: Development Build

on:
  push:
    branches: [ NUM-17-github-action-to-build-push-to-dockerhub ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Docker build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: b6wong/dominion-record-backend
        tags: latest
